package com.clause.app.domain.rules.enums;

public enum RuleCategory {
    PENALTY,
    DAMAGES_UNLIMITED,
    INDEMNITY,
    LIABILITY_WAIVER,
    UNILATERAL_TERMINATION,
    TERMINATION_NOTICE,
    AUTO_RENEW,
    UNILATERAL_CHANGE,
    JURISDICTION,
    ARBITRATION,
    GOVERNING_LAW,
    IP_ASSIGNMENT,
    CONFIDENTIALITY_BROAD,
    CONFIDENTIALITY_TERM,
    NON_COMPETE,
    NON_SOLICIT,
    DATA_CONSENT,
    AUDIT_ACCESS,
    DEPOSIT_DEDUCTION,
    REPAIR_RESTORE,
    PAYMENT,
    ACCEPTANCE_CRITERIA,
    SCOPE_CHANGE,
    ASSIGNMENT_CLAUSE,
    ENTIRE_AGREEMENT,
    NOTICES,
    FORCE_MAJEURE
}

